# Generated by Django 2.0.4 on 2018-05-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='operationcompta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useridsaisie', models.IntegerField(null=True)),
                ('useridimputer', models.IntegerField(null=True)),
                ('typejournal_idtypejournal', models.PositiveIntegerField()),
                ('libelle', models.CharField(blank=True, max_length=45, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('prixunitaire', models.FloatField(blank=True, null=True)),
                ('dateoperation', models.DateField(blank=True, null=True)),
                ('datesaisie', models.DateField(blank=True, null=True)),
                ('dateimput', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=45, null=True)),
                ('quantité', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='liaison',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
