# Generated by Django 2.0.4 on 2018-05-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0004_customuser_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
