# Generated by Django 2.0.4 on 2018-05-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0004_operationcompta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
