# Generated by Django 2.0.4 on 2018-05-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0005_auto_20180505_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_see_dealer_price', 'Can see dealer price'),)},
        ),
    ]
