# Generated by Django 2.0.4 on 2018-05-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0006_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fournisseurs',
        ),
    ]
