# Generated by Django 2.0.4 on 2018-05-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0008_auto_20180507_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
