# Generated by Django 2.0.4 on 2018-05-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0009_liaison'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compte',
            options={},
        ),
    ]
