# Generated by Django 2.0.4 on 2018-05-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0010_auto_20180522_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compte',
        ),
    ]
