# Generated by Django 2.0.4 on 2018-05-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0010_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
