# Generated by Django 2.0.4 on 2018-05-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0011_delete_compte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('compteid', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=45, null=True)),
                ('classe', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
