# Generated by Django 2.0.4 on 2018-05-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0012_compte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={},
        ),
    ]
