# Generated by Django 2.0.4 on 2018-05-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0013_auto_20180522_1209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
