# Generated by Django 2.0.4 on 2018-05-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0014_auto_20180509_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='autorisé',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='standard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='validé',
            field=models.BooleanField(default=False),
        ),
    ]
