# Generated by Django 2.0.4 on 2018-05-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0014_delete_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('idcredit', models.AutoField(primary_key=True, serialize=False)),
                ('operation_operationid', models.IntegerField()),
                ('compte_compteid', models.IntegerField()),
                ('operation_user_2_useridsaisie', models.IntegerField()),
                ('operation_user_2_useridimputer', models.IntegerField()),
                ('operation_typejournal_idtypejournal', models.PositiveIntegerField()),
                ('double_2', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
