# Generated by Django 2.0.4 on 2018-05-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0015_credit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debit',
            options={},
        ),
    ]
