# Generated by Django 2.0.4 on 2018-05-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0015_auto_20180511_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='autorisé',
            new_name='autorise',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='validé',
            new_name='valide',
        ),
    ]
