# Generated by Django 2.0.4 on 2018-05-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0016_auto_20180522_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Debit',
        ),
    ]
