# Generated by Django 2.0.4 on 2018-05-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0016_auto_20180511_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='valide',
            new_name='valides',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='autorise',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='standard',
        ),
        migrations.AddField(
            model_name='customuser',
            name='autorises',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='standards',
            field=models.BooleanField(default=True),
        ),
    ]
