# Generated by Django 2.0.4 on 2018-05-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0018_debit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typejournal',
            options={},
        ),
    ]
