# Generated by Django 2.0.4 on 2018-05-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0019_auto_20180522_1211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Typejournal',
        ),
    ]
