# Generated by Django 2.0.4 on 2018-05-11 15:09

import comptaApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0019_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='entreprise',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=comptaApp.models.user_directory_path),
        ),
    ]
