# Generated by Django 2.0.4 on 2018-05-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0020_delete_typejournal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typejournal',
            fields=[
                ('idtypejournal', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
