# Generated by Django 2.0.4 on 2018-05-23 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0022_operationcompta_fournisseurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='double_2',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='operation_operationid',
        ),
        migrations.RemoveField(
            model_name='debit',
            name='operation_operationid',
        ),
        migrations.AddField(
            model_name='credit',
            name='montant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='operationid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comptaApp.operationcompta'),
        ),
        migrations.AddField(
            model_name='debit',
            name='operationid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comptaApp.operationcompta'),
        ),
    ]
