# Generated by Django 2.0.4 on 2018-05-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0023_auto_20180523_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='compte_compteid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='operation_typejournal_idtypejournal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='operation_user_2_useridimputer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='operation_user_2_useridsaisie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debit',
            name='compte_compteid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debit',
            name='operation_typejournal_idtypejournal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debit',
            name='operation_user_2_useridimputer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debit',
            name='operation_user_2_useridsaisie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
