# Generated by Django 2.0.4 on 2018-05-24 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0024_auto_20180523_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationcompta',
            name='fournisseurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
