# Generated by Django 2.0.4 on 2018-05-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0025_auto_20180524_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debit',
            name='montant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
