# Generated by Django 2.0.4 on 2018-05-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0026_auto_20180530_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debit',
            name='montant',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
