# Generated by Django 2.0.4 on 2018-06-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0028_auto_20180601_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saisieon',
            field=models.BooleanField(default=False),
        ),
    ]
