# Generated by Django 2.0.4 on 2018-06-19 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0029_customuser_saisieon'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_saisie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='userid_saisie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
