# Generated by Django 2.0.4 on 2018-07-06 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0032_auto_20180620_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='imputation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misajour', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='comptaApp.operationcompta')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='credit',
            name='operation_typejournal_idtypejournal',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='operation_user_2_useridimputer',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='operation_user_2_useridsaisie',
        ),
    ]