# Generated by Django 2.0.4 on 2018-07-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0033_auto_20180706_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imputation',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='imputation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='operationid',
        ),
        migrations.RemoveField(
            model_name='debit',
            name='operation_typejournal_idtypejournal',
        ),
        migrations.RemoveField(
            model_name='debit',
            name='operation_user_2_useridimputer',
        ),
        migrations.RemoveField(
            model_name='debit',
            name='operation_user_2_useridsaisie',
        ),
        migrations.RemoveField(
            model_name='debit',
            name='operationid',
        ),
        migrations.DeleteModel(
            name='imputation',
        ),
    ]