# Generated by Django 2.0.4 on 2018-07-06 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0035_auto_20180706_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='reglement',
            fields=[
                ('modereglementid', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='operationcompta',
            old_name='dateimput',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='operationcompta',
            old_name='useridimputer',
            new_name='useridtranscription',
        ),
        migrations.RemoveField(
            model_name='operationcompta',
            name='datesaisie',
        ),
        migrations.RemoveField(
            model_name='operationcompta',
            name='useridsaisie',
        ),
        migrations.AddField(
            model_name='operationcompta',
            name='modereglementid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='comptaApp.reglement'),
        ),
    ]