# Generated by Django 2.0.4 on 2018-07-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0036_auto_20180706_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='libellecompte',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='debit',
            name='libellecompte',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]