# Generated by Django 2.0.4 on 2018-08-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptaApp', '0039_auto_20180810_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='typedeclaration',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
